#include "simpleVTIsoPool.xml-variables.inc"
#include "simpleVTIsoPool.xml-attributes.inc"
#include "simpleVTIsoPool.xml-list.inc"
#include "simpleVTIsoPool.xml-defines.inc"
#include "simpleVTIsoPool.xml-functions.inc"
