/*
  vtobjectsoftkeymask_c.cpp

  (C) Copyright 2009 - 2016 by OSB AG and developing partners

  See the repository-log for details on the authors and file-history.
  (Repository information can be found at <http://isoaglib.com/download>)

  Use, modification and distribution are subject to the GNU General
  Public License with exceptions for ISOAgLib. (See accompanying
  file LICENSE.txt or copy at <http://isoaglib.com/download/license>)
*/

#include "vtobjectsoftkeymask_c.h"
#include "../ivtobjectmacro_c.h"

#include "vtclient_c.h"

#ifdef ENABLE_SKM_HANDLER
#  ifdef DEFAULT_SKM_HANDLER_HEADER
#    include DEFAULT_SKM_HANDLER_HEADER
#  endif // DEFAULT_SKM_HANDLER_HEADER
#endif // ENABLE_SKM_HANDLER

namespace __IsoAgLib {

int16_t
vtObjectSoftKeyMask_c::stream(uint8_t* destMemory,
                              uint16_t maxBytes,
                              objRange_t sourceOffset)
{
#define MACRO_vtObjectTypeA vtObjectSoftKeyMask_a
#define MACRO_vtObjectTypeS iVtObjectSoftKeyMask_s
  MACRO_streamLocalVars;

  const uint8_t numberOfObjectsToFollow = get_numberOfObjectsToFollow();

  if (__IsoAgLib::getVtClientInstance4Comm().getClientByID (s_properties.clientId)
      .getVtServerInst().getVtCapabilities().skVirtual < numberOfObjectsToFollow)
  { // can't upload this SKM because it has more Keys than virtually supported
    return 0;
  }

  if (sourceOffset == 0) { // dump out constant sized stuff
    destMemory [0] = vtObject_a->ID & 0xFF;
    destMemory [1] = vtObject_a->ID >> 8;
    destMemory [2] = 4; // Object Type = Soft Key Mask
    destMemory [3] = __IsoAgLib::getVtClientInstance4Comm().getClientByID (s_properties.clientId).getUserConvertedColor (vtObjectSoftKeyMask_a->backgroundColour, this, IsoAgLib::BackgroundColour);
    destMemory [4] = numberOfObjectsToFollow;
    destMemory [5] = vtObjectSoftKeyMask_a->numberOfMacrosToFollow;

    sourceOffset += 6;
    curBytes += 6;
  }

  if( numberOfObjectsToFollow )
  {
#ifdef ENABLE_SKM_HANDLER
    if( m_SkmHandler )
    {
      const objRange_t bytesBefore = 6;

      uint16_t nrObject = (sourceOffset - (bytesBefore)) / 2;
      while( (sourceOffset >= (bytesBefore)) && (sourceOffset < ((bytesBefore)+2U * numberOfObjectsToFollow)) && ((curBytes + 2) <= maxBytes) )
      {
        const iVtObject_c* vtObject = m_SkmHandler->objectsToFollow( nrObject );
        if( vtObject )
        {
          /* write out an object */
          if( vtObject != NULL )
          {
              destMemory[curBytes] = vtObject->getID() & 0xFF;
              destMemory[curBytes + 1] = vtObject->getID() >> 8;
          }
          else
          {
              destMemory[curBytes] = 0xFF;
              destMemory[curBytes + 1] = 0xFF;
          }
          curBytes += 2;
        }
        sourceOffset += 2;
        nrObject++;
      }
    }
    else
#endif // ENABLE_SKM_HANDLER
    {
       MACRO_streamObject( 6 );
    }
  }

  MACRO_streamEventMacro(6+vtObjectSoftKeyMask_a->numberOfObjectsToFollow*2U);
  return curBytes;
}

uint8_t vtObjectSoftKeyMask_c::get_numberOfObjectsToFollow() const
{
  MACRO_localVars;

#ifdef ENABLE_SKM_HANDLER
  if( m_SkmHandler )
  {
    return m_SkmHandler->numberOfObjectsToFollow();
  }
  else
#endif // ENABLE_SKM_HANDLER
  {
    return vtObjectSoftKeyMask_a->numberOfObjectsToFollow;
  }
}

vtObjectSoftKeyMask_c::vtObjectSoftKeyMask_c()
#ifdef ENABLE_SKM_HANDLER
  : m_SkmHandler( NULL )
  , b_autoGenerated_SkmHandler( false )
#endif // ENABLE_SKM_HANDLER
{
}

vtObjectSoftKeyMask_c::~vtObjectSoftKeyMask_c()
{
#ifdef ENABLE_SKM_HANDLER
  if( b_autoGenerated_SkmHandler )
  {
    // Assume that the destructor below will callback unRegisterSkmHandler which will reset the m_SkmHandler
    delete m_SkmHandler;
    b_autoGenerated_SkmHandler = false;
  }

  isoaglib_assert( m_SkmHandler == NULL );
#endif // ENABLE_SKM_HANDLER
}

#ifdef ENABLE_SKM_HANDLER
void vtObjectSoftKeyMask_c::registerSkmHandler_c( iSkmHandler_c* _SkmHandler )
{
  isoaglib_assert( m_SkmHandler == NULL );
  m_SkmHandler = _SkmHandler;
}

void vtObjectSoftKeyMask_c::unRegisterSkmHandler_c( iSkmHandler_c* _SkmHandler )
{
  isoaglib_assert( m_SkmHandler == _SkmHandler );
  m_SkmHandler = NULL;
}
#endif // ENABLE_SKM_HANDLER


uint32_t
vtObjectSoftKeyMask_c::fitTerminal() const
{
  MACRO_localVars;

  const uint8_t skVirtual = __IsoAgLib::getVtClientInstance4Comm().getClientByID( s_properties.clientId ).getVtServerInst().getVtCapabilities().skVirtual;

#ifdef ENABLE_SKM_HANDLER

#  ifdef DEFAULT_SKM_HANDLER_C
  // If this skm doesn't have a handler, but needs one, then auto-create it
  if (!m_SkmHandler)
  {
    if( skVirtual < vtObjectSoftKeyMask_a->numberOfObjectsToFollow )
    {
      // Assume that the constructor below will callback registerSkmHandler which will set the m_SkmHandler
      new DEFAULT_SKM_HANDLER_C( __IsoAgLib::getVtClientInstance4Comm().getClientByID( s_properties.clientId ).getPool(), *(IsoAgLib::iVtObjectSoftKeyMask_c*)this );
      b_autoGenerated_SkmHandler = true;
    }
  }
#  endif // DEFAULT_SKM_HANDLER_C

  if( m_SkmHandler )
  {
    m_SkmHandler->fitTerminal();
  }
#endif // ENABLE_SKM_HANDLER

  const uint8_t numberOfObjectsToFollow = get_numberOfObjectsToFollow();

  if ( skVirtual < numberOfObjectsToFollow )
  { // can't upload this SKM because it has more Keys than virtually supported
    return 0;
  }
  else
  { // okay, enough virtual SKs supported, so upload this SKM
    return 6 + (numberOfObjectsToFollow*2) + (vtObjectSoftKeyMask_a->numberOfMacrosToFollow*2);
  }
}


void
vtObjectSoftKeyMask_c::setOriginSKM(bool /*b_SKM*/)
{
  MACRO_localVars;
  for (int i=0; i<vtObjectSoftKeyMask_a->numberOfObjectsToFollow; i++) {
    vtObjectSoftKeyMask_a->objectsToFollow[i].vtObject->setOriginSKM (true);
  }
}
#ifdef USE_ISO_TERMINAL_GETATTRIBUTES
uint8_t
vtObjectSoftKeyMask_c::updateBackgroundColour(bool b_SendRequest)
{
  if (b_SendRequest)
    return getValue8GetAttribute(MACRO_getStructOffset(get_vtObjectSoftKeyMask_a(), backgroundColour), sizeof(iVtObjectSoftKeyMask_s), 1);
  else
    return getValue8(MACRO_getStructOffset(get_vtObjectSoftKeyMask_a(), backgroundColour), sizeof(iVtObjectSoftKeyMask_s));
}

void
vtObjectSoftKeyMask_c::saveReceivedAttribute(uint8_t attrID, uint8_t* pui8_attributeValue)
{
  if (attrID == 1)
    saveValue8(MACRO_getStructOffset(get_vtObjectSoftKeyMask_a(), backgroundColour), sizeof(iVtObjectSoftKeyMask_s), convertLittleEndianStringUi8(pui8_attributeValue));
}
#endif

} // __IsoAgLib
